/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic_PreprocessMessages = require('./code/customermessage-logic-preprocessMessages');

class bTPGenAI4S4_StudentAmer47_ex2Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessage', async (request) => {
            await customermessage_Logic_PreprocessMessages(request);
        });

        return super.init();
    }
}


module.exports = {
    bTPGenAI4S4_StudentAmer47_ex2Srv
};